// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srbcrpvifcozcbrqpsqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyYmNycHZpZmNvemNicnFwc3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjY0MzcsImV4cCI6MjA3MjMwMjQzN30.dQuijB0qXFjbEJlu-1rkA7l25tAeCuReSJfM8iuSPzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});